bookstore_online/apps/bookstore_goods/urls.py
# coding=utf-8
from django.conf.urls import url

from . import views

app_name = 'bookstore_goods'

urlpatterns = [
    url('^$', views.index, name="index"),
    url('^list(\d+)_(\d+)_(\d+)/$', views.good_list, name="good_list"),
    url('^(\d+)/$', views.detail, name="detail"),
    url(r'^search/', views.ordinary_search, name="ordinary_search"),  # 全文检索
]

bookstore_online/apps/bookstore_user/urls.py
# coding=utf-8
from django.conf.urls import url

from .import views

app_name = 'bookstore_user'

urlpatterns = [
    url(r'^register/$', views.register, name="register"),
    url(r'^register_handle/$', views.register_handle, name="register_handle"),
    url(r'^register_exist/$', views.register_exist, name="register_exist"),
    url(r'^login/$', views.login, name="login"),
    url(r'^login_handle/$', views.login_handle, name="login_handle"),
    url(r'^info/$', views.info, name="info"),
    url(r'^order/(\d+)$',views.order, name="order"),
    url(r'^site/$', views.site, name="site"),
    url(r'^logout/$', views.logout, name="logout"),
]

bookstore_online/bookstore_online/urls.py
#coding=utf-8
"""bookstore_online URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('bookstore_goods.urls', namespace='bookstore_goods')),
    url(r'^user/', include('bookstore_user.urls', namespace='bookstore_user')),
    url(r'^cart/', include('bookstore_cart.urls', namespace='bookstore_cart')),
    url(r'^order/', include('bookstore_order.urls', namespace='bookstore_order')),
    url(r'^tinymce/', include('tinymce.urls')),  # 使用富文本编辑框配置conf
]

bookstore_online/apps/bookstore_goods/models.py
# coding=utf-8
from django.db import models
from tinymce.models import HTMLField  # 使用富文本编辑框要在settings文件中安装
# 将一对多的关系维护在GoodsInfo中维护，另外商品信息与分类信息都属于重要信息需要使用逻辑删除


class TypeInfo(models.Model):
    # 图书分类
    isDelete = models.BooleanField(default=False)
    ttitle = models.CharField(max_length=20, verbose_name="分类")

    class Meta:
        verbose_name = "商品类型"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ttitle


class GoodsInfo(models.Model):
    # 具体图书信息
    isDelete = models.BooleanField(default=False)  # 逻辑删除
    gtitle = models.CharField(max_length=50, verbose_name="图书名称", unique=True)
    gpicture = models.ImageField(upload_to='bookstore_goods', verbose_name="图片路径")
    gprice = models.DecimalField(max_digits=5, decimal_places=2, verbose_name="商品价格")  # 商品价格小数位为两位，整数位为3位
    author = models.CharField(max_length=50,verbose_name='作者')
    press = models.CharField(max_length=50,verbose_name='出版社')
    publictime = models.CharField(max_length=20,verbose_name='出版时间')
    gclick = models.IntegerField(verbose_name="点击量")
    gintroduction = models.CharField(max_length=200, verbose_name="简介")
    gstock = models.IntegerField(verbose_name="库存")
    gdetails = HTMLField(max_length=10000, verbose_name="详情")
    gtype = models.ForeignKey(TypeInfo, on_delete=models.CASCADE, verbose_name="分类")  # 外键关联TypeInfo表


    class Meta:
        verbose_name = "商品"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.gtitle

bookstore_online/apps/bookstore_goods/views.py
#coding=utf-8
from django.core.paginator import Paginator
from django.shortcuts import render

from .models import GoodsInfo, TypeInfo
from bookstore_cart.models import CartInfo
from bookstore_user.models import BooksBrowser


def index(request):
    # 查询各个分类的最新4条，最热4条数据
    typelist = TypeInfo.objects.all()
    #  _set 连表操作
    type0 = typelist[0].goodsinfo_set.order_by('-id')[0:4]  # 按照上传顺序
    type01 = typelist[0].goodsinfo_set.order_by('-gclick')[0:4]  # 按照点击量
    type1 = typelist[1].goodsinfo_set.order_by('-id')[0:4]
    type11 = typelist[1].goodsinfo_set.order_by('-gclick')[0:4]
    type2 = typelist[2].goodsinfo_set.order_by('-id')[0:4]
    type21 = typelist[2].goodsinfo_set.order_by('-gclick')[0:4]
    type3 = typelist[3].goodsinfo_set.order_by('-id')[0:4]
    type31 = typelist[3].goodsinfo_set.order_by('-gclick')[0:4]
    type4 = typelist[4].goodsinfo_set.order_by('-id')[0:4]
    type41 = typelist[4].goodsinfo_set.order_by('-gclick')[0:4]
    type5 = typelist[5].goodsinfo_set.order_by('-id')[0:4]
    type51 = typelist[5].goodsinfo_set.order_by('-gclick')[0:4]

    cart_num = 0
    # 判断是否存在登录状态
    if 'user_id' in request.session:
        user_id = request.session['user_id']
        cart_num = CartInfo.objects.filter(user_id=int(user_id)).count()

    context = {
        'title': '首页',
        'cart_num': cart_num,
        'guest_cart': 1,
        'type0': type0, 'type01': type01,
        'type1': type1, 'type11': type11,
        'type2': type2, 'type21': type21,
        'type3': type3, 'type31': type31,
        'type4': type4, 'type41': type41,
        'type5': type5, 'type51': type51,
    }

    return render(request, 'bookstore_goods/index.html', context)


def good_list(request, tid, pindex, sort):
    # tid：商品种类信息  pindex：商品页码 sort：商品显示分类方式
    typeinfo = TypeInfo.objects.get(pk=int(tid))

    # 根据主键查找当前的图书分类
    news = typeinfo.goodsinfo_set.order_by('-id')[0:2]
    # list.html左侧最新商品推荐
    goods_list = []
    # list中间栏商品显示方式
    cart_num, guest_cart = 0, 0
    user_id = request.session['user_id']
    if user_id:
        guest_cart = 1
        cart_num = CartInfo.objects.filter(user_id=int(user_id)).count()

    if sort == '1':  # 默认最新
        goods_list = GoodsInfo.objects.filter(gtype_id=int(tid)).order_by('-id')
    elif sort == '2':  # 按照价格
        goods_list = GoodsInfo.objects.filter(gtype_id=int(tid)).order_by('-gprice')
    elif sort == '3':  # 按照人气点击量
        goods_list = GoodsInfo.objects.filter(gtype_id=int(tid)).order_by('-gclick')

    # 创建Paginator一个分页对象
    paginator = Paginator(goods_list, 4)
    # 返回Page对象，包含商品信息
    page = paginator.page(int(pindex))
    context = {
        'title': '商品列表',
        'guest_cart': guest_cart,
        'cart_num': cart_num,
        'page': page,
        'paginator': paginator,
        'typeinfo': typeinfo,
        'sort': sort,  # 排序方式
        'news': news,
    }
    return render(request, 'bookstore_goods/list.html', context)


def detail(request, gid):
    good_id = gid
    goods = GoodsInfo.objects.get(pk=int(good_id))
    goods.gclick = goods.gclick + 1  # 商品点击量
    goods.save()

    news = goods.gtype.goodsinfo_set.order_by('-id')[0:2]
    context = {
        'title': goods.gtype.ttitle,
        'guest_cart': 1,
        'cart_num': cart_count(request),
        'goods': goods,
        'news': news,
        'id': good_id,
    }
    response = render(request, 'bookstore_goods/detail.html', context)

    if 'user_id' in request.session:
        user_id = request.session["user_id"]
        try:
            browsed_good = BooksBrowser.objects.get(user_id=int(user_id), good_id=int(good_id))
        except Exception:
            browsed_good = None
        if browsed_good:
            from datetime import datetime
            browsed_good.browser_time = datetime.now()
            browsed_good.save()
        else:
            BooksBrowser.objects.create(user_id=int(user_id), good_id=int(good_id))
            browsed_goods = BooksBrowser.objects.filter(user_id=int(user_id))
            browsed_good_count = browsed_goods.count()
            if browsed_good_count > 5:
                ordered_goods = browsed_goods.order_by("-browser_time")
                for _ in ordered_goods[5:]:
                    _.delete()
    return response


def cart_count(request):
    if 'user_id' in request.session:
        return CartInfo.objects.filter(user_id=request.session['user_id']).count
    else:
        return 0


def ordinary_search(request):
    #Q:对对象进行复杂查询
    from django.db.models import Q

    search_keywords = request.GET.get('q', '')
    pindex = request.GET.get('pindex', 1)
    search_status = True
    cart_num, guest_cart = 0, 0

    try:
        user_id = request.session['user_id']
    except:
        user_id = None

    if user_id:
        guest_cart = 1
        cart_num = CartInfo.objects.filter(user_id=int(user_id)).count()

    if search_keywords:
        goods_list = GoodsInfo.objects.filter(
            Q(gtitle__icontains=search_keywords) |
            Q(gdetails__icontains=search_keywords) |
            Q(gintroduction__icontains=search_keywords)).order_by("gclick")
    else:
        search_status = False
        goods_list = GoodsInfo.objects.all().order_by("gclick")

    paginator = Paginator(goods_list, 4)
    page = paginator.page(int(pindex))

    context = {
        'title': '搜索列表',
        'search_status': search_status,
        'guest_cart': guest_cart,
        'cart_num': cart_num,
        'page': page,
        'paginator': paginator,
    }
    return render(request, 'bookstore_goods/ordinary_search.html', context)

bookstore_online/templates/bookstore_goods/base.html
{% extends 'base.html' %}

{% block center_body %}

    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>图书分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="/list1_1_1/" class="art">文学艺术</a></li>
					<li><a href="/list2_1_1/" class="science">人文社科</a></li>
					<li><a href="/list3_1_1/" class="technology">科学技术</a></li>
					<li><a href="/list4_1_1/" class="children">少儿读物</a></li>
					<li><a href="/list5_1_1/" class="life">健康生活</a></li>
					<li><a href="/list6_1_1/" class="education">考试教育</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url "bookstore_goods:index" %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动书店</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		图书分类 > {{ title }}
		{% if id|default:' ' != ' ' %}
        > 商品详情
		{% endif %}
	</div>

{% block center_content %}

{% endblock center_content %}



{% endblock center_body %}

bookstore_online/templates/bookstore_goods/detail.html
{% extends 'bookstore_goods/base.html' %}

{% block head %}
    <script type="text/javascript">

{#  通过绑定js事件实现随着商品数量的增长商品总价上涨#}
    function plus() {
        num = parseFloat($('.num_show').val());
        stock = parseFloat($('.goods_stock').html());
        if(num<=stock){
            $('.num_show').val(num+1);
            $('.num_show').blur();
        }
    }

    function minus() {
        num = parseFloat($('.num_show').val());
        if(num>1)
        {
            $('.num_show').val(num-1);
            $('.num_show').blur();
        }
        else {
            {#商品的数量不可以小于1#}
        }
    }

    $(function () {
        $('.num_show').blur(function () {

        num = parseInt($('.num_show').val());

        if(num<=1)
             num = 1;

         stock = parseInt($('.goods_stock').text());

         if(num>=stock)
             num = stock;

         price = parseFloat($('#gprice').text());
         total = num*price;
         $('.num_show').val(num);
         $('#gtotal').text(total.toFixed(2)+'元');

{#             $('add_cart').attr('href', '/cart/add'+$('gid').val())#}
        });
    });
    </script>

{% endblock head %}

{% block center_content %}
	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="/static/{{ goods.gpicture }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.gtitle }}</h3>
			<p>{{ goods.gintroduction}}</p>
			<p>{{ goods.author }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em id="gprice">{{ goods.gprice }}</em></span>
				<span class="show_unit">出版社：{{ goods.press }}</span>
				<span class="show_unit">出版时间：{{ goods.publictime }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:plus();" class="add fr">+</a>
					<a href="javascript:minus();" class="minus fr">-</a>
				</div>
			</div>
			<div class="total">总价：<em id="gtotal">{{ goods.gprice }}元</em></div>
			<div class="operate_btn">
                {% if request.session.user_name|default:'' != '' %}
                    <a href="javascript:;" class="buy_btn" id="buy_now">立即购买</a>
                {% else %}
                    <a href="{% url "bookstore_user:login" %}" class="buy_btn">立即购买</a>
                {% endif %}
                {% if request.session.user_name|default:'' != '' %}
                    <a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
                {% else %}
                    <a href="{% url "bookstore_user:login" %}" class="add_cart" id="add_cart">加入购物车</a>
                {% endif %}
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for goods in news %}
					<li>
						<a href="/{{ goods.id }}"><img src="/static/{{ goods.gpicture }}"></a>
						<h4><a href="#">{{ goods.gtitle }}</a></h4>
						<div class="prize">￥{{ goods.gprice }}</div>
					</li>
                    {%  endfor %}
                </ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>图书详情：</dt>
					<dd>{{ goods.gdetails|safe }}</dd>
				</dl>
			</div>

		</div>
	</div>

	<div class="add_jump"></div>

	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
    $(document).ready(function(){

        $(".buy_btn").click(function () {
            num = parseInt($('.num_show').val());
            $.get('/cart/add{{ goods.id }}_'+num+'/',function (data) {
                $('#show_count').text(data.count);
            });
            location.href = "/cart/";

        });

        $('#add_cart').click(function() {

            var $add_x = $('#add_cart').offset().top;
            var $add_y = $('#add_cart').offset().left;

            var $to_x = $('#show_count').offset().top;
            var $to_y = $('#show_count').offset().left;

            $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'});

            $('#add_cart').click(function() {

    {#            		    先判断是否登录#}
                if ($('.login_btn').text().indexOf('登录') >= 0) {
                    alert('请登陆后购买');
                    location.href('/user/login/');
                    return;
                }

    {#                        购物车添加动画#}
                $(".add_jump").stop().animate({
                        'left': $to_y + 7,
                        'top': $to_x + 7
                    },
                    "fast", function () {
                        $(".add_jump").fadeOut('fast', function () {
                            count = $('.num_show').val();
                            $('#show_count').html(count);
                    });
                });

                num = parseInt($('.num_show').val());
                $.get('/cart/add{{ goods.id }}_'+num+'/',function (data) {
                    $('#show_count').text(data.count);
                });
            });
        });

    });
	</script>

{% endblock center_content %}

bookstore_online/templates/bookstore_goods/index.html
{% extends 'base.html' %}

{% block head %}
    <script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
{% endblock head %}

{% block center_body %}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">图书分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url "bookstore_goods:index" %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="#">移动书店</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="art">文学艺术</a></li>
			<li><a href="#model02" class="science">人文社科</a></li>
			<li><a href="#model03" class="technology">科学技术</a></li>
			<li><a href="#model04" class="children">少儿读物</a></li>
			<li><a href="#model05" class="life">健康生活</a></li>
			<li><a href="#model06" class="education">考试教育</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/artslide.png" alt="幻灯片"></li>
				<li><img src="/static/images/scienceslide.png" alt="幻灯片"></li>
				<li><img src="/static/images/technologyslide.png" alt="幻灯片"></li>
				<li><img src="/static/images/childrenslide.png" alt="幻灯片"></li>
				<li><img src="/static/images/lifeslide.png" alt="幻灯片"></li>
				<li><img src="/static/images/educationslide.png" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv_01.png"></a>
			<a href="#"><img src="/static/images/adv_02.png"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">文学艺术</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for g in type01 %}
                    <a href="/{{ g.id }}/">{{  g.gtitle|slice:'10' }}</a>
                {%  endfor %}
			</div>
			<a href="/list1_1_1/" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/artbanner.png"></div>
			<ul class="goods_list fl">
                {% for goods in type0 %}
                <li>
                    <h4><a href="/{{ goods.id }}/">{{ goods.gtitle }}</a></h4>
                    <a href="/{{ goods.id }}/"><img src="/static/{{ goods.gpicture }}"></a>
                    <div class="prize"> ￥ {{ goods.gprice }} </div>
                </li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">人文社科</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for g in type1 %}
                    <a href="/{{ g.id }}/">{{ g.gtitle|slice:'10' }}</a>
                {% endfor %}
			</div>
			<a href="/list2_1_1/" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/sciencebanner.png"></div>
			<ul class="goods_list fl">
                {% for goods in type11 %}
                <li>
                    <h4><a href="/{{ goods.id }}/">{{ goods.gtitle }}</a></h4>
                    <a href="/{{ goods.id }}/"><img src="/static/{{ goods.gpicture }}"></a>
                    <div class="prize"> ￥ {{ goods.gprice }} </div>
                </li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">科学技术</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for g in type2 %}
                    <a href="/{{ g.id }}/">{{ g.gtitle|slice:'10' }}</a>
                {% endfor %}
			</div>
			<a href="/list3_1_1/" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/technologybanner.png"></div>
			<ul class="goods_list fl">
				{% for goods in type21 %}
                <li>
                    <h4><a href="/{{ goods.id }}/">{{ goods.gtitle }}</a></h4>
                    <a href="/{{ goods.id }}/"><img src="/static/{{ goods.gpicture }}"></a>
                    <div class="prize"> ￥ {{ goods.gprice }} </div>
                </li>
                {% endfor %}
				</li>
			</ul>
		</div>

	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">少儿读物</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for g in type3 %}
                    <a href="/{{ g.id }}/">{{ g.gtitle|slice:'10' }}</a>
                {% endfor %}
			</div>
			<a href="/list4_1_1/" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/childrenbanner.png"></div>
			<ul class="goods_list fl">
				{% for goods in type31 %}
                <li>
                    <h4><a href="/{{ goods.id }}/">{{ goods.gtitle }}</a></h4>
                    <a href="/{{ goods.id }}/"><img src="/static/{{ goods.gpicture }}"></a>
                    <div class="prize"> ￥ {{ goods.gprice }} </div>
                </li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">健康生活</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for g in type4 %}
                    <a href="/{{ g.id }}/">{{ g.gtitle|slice:'10' }}</a>
                {% endfor %}
			</div>
			<a href="/list5_1_1/" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/lifebanner.png"></div>
			<ul class="goods_list fl">
				{% for goods in type41 %}
                <li>
                    <h4><a href="/{{ goods.id }}/">{{ goods.gtitle }}</a></h4>
                    <a href="/{{ goods.id }}/"><img src="/static/{{ goods.gpicture }}"></a>
                    <div class="prize"> ￥ {{ goods.gprice }} </div>
                </li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">考试教育</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for g in type5 %}
                    <a href="/{{ g.id }}/">{{ g.gtitle|slice:'10' }}</a>
                {% endfor %}
			</div>
			<a href="/list6_1_1/" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/educationbanner.png"></div>
			<ul class="goods_list fl">
				{% for goods in type51 %}
                <li>
                    <h4><a href="/{{ goods.id }}/">{{ goods.gtitle }}</a></h4>
                    <a href="/{{ goods.id }}/"><img src="/static/{{ goods.gpicture }}"></a>
                    <div class="prize"> ￥ {{ goods.gprice }} </div>
                </li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<script type="text/javascript" src="/static/js/slide.js"></script>
    <script type="text/javascript">
        BCSlideshow('focuspic');
        var oFruit = document.getElementById('fruit_more');
        var oShownum = document.getElementById('show_count');

        var hasorder = localStorage.getItem('order_finish');

        if(hasorder)
        {
        oShownum.innerHTML = '2';
        }

        oFruit.onclick = function(){
        window.location.href = 'list.html';
        }
    </script>

{% endblock center_body %}

bookstore_online/templates/bookstore_goods/ordinary_search.html
{% extends 'base.html' %}
{% block center_body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>图书分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="/list1_1_1" class="art">文学艺术</a></li>
			        <li><a href="/list2_1_1" class="science">人文社科</a></li>
			        <li><a href="/list3_1_1" class="technology">科学技术</a></li>
			        <li><a href="/list4_1_1" class="children">少儿读物</a></li>
			        <li><a href="/list5_1_1" class="life">健康生活</a></li>
			        <li><a href="/list6_1_1" class="education">考试教育</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url "bookstore_goods:index" %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动书店</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		图书分类
{#        {{ title }}#}
{#		{% if id|default:' ' != ' ' %}#}
        > 商品详情
{#		{% endif %}#}
	</div>

    <div class="main_wrap clearfix">
        <ul class="goods_type_list clearfix">
            {%  for item in page %}
            <li>
                <a href="/{{ item.id }}/"><img src="/static/{{ item.gpicture }}/"></a>
                <h4><a href="/{{ item.id }}/">{{ item.gtitle }}</a></h4>
                <div class="operate">
                    <span class="prize">￥{{ item.gprice }}</span>
                    <a href="/cart/add{{ item.id }}_1/" class="add_goods" title="加入购物车"></a>
{#						<a href="javasript:;/" class="add_goods" title="加入购物车"></a>#}
                </div>
            </li>
            {% endfor %}
        </ul>
        <div class="pagenation">
{#                判断是否是第一页#}
            {% if page.has_previous %}
                <a href="{% url "bookstore_user:ordinary_search" %}?q={{ query }}&amp;page={{ page.previous_page_number }}">上一页</a>
            {% endif %}

            {% for pindex in paginator.page_range %}
                {% if pindex == page.number %}
                    <a href="#" class="active">{{ pindex }}</a>
                {% else %}
                    <a href="{% url "bookstore_user:ordinary_search" %}?q={{ query }}&amp;page={{ pindex }}">{{ pindex }}</a>
                {% endif %}
            {% endfor %}

{#                是否又第二页#}
            {% if page.has_next %}
                <a href="{% url "bookstore_user:ordinary_search" %}?q={{ query }}&amp;page={{ page.next_page_number }}">下一页></a>
            {% endif %}
        </div>
    </div>
{% endblock center_body %}