bookstore_online/apps/bookstore_cart/urls.py
# coding=utf-8
from django.conf.urls import url

from . import views

app_name = 'bookstore_cart'

urlpatterns = [
    url(r'^$', views.user_cart, name="cart"),
    url(r'^add(\d+)_(\d+)/$', views.add, name="add"),
    url(r'^edit(\d+)_(\d+)/$', views.edit, name="edit"),
    url(r'^delete(\d+)/$', views.delete, name="delete"),
]

bookstore_online/apps/bookstore_goods/urls.py
# coding=utf-8
from django.conf.urls import url

from . import views

app_name = 'bookstore_goods'

urlpatterns = [
    url('^$', views.index, name="index"),
    url('^list(\d+)_(\d+)_(\d+)/$', views.good_list, name="good_list"),
    url('^(\d+)/$', views.detail, name="detail"),
    url(r'^search/', views.ordinary_search, name="ordinary_search"),  # 全文检索
]

bookstore_online/apps/bookstore_user/urls.py
# coding=utf-8
from django.conf.urls import url

from .import views

app_name = 'bookstore_user'

urlpatterns = [
    url(r'^register/$', views.register, name="register"),
    url(r'^register_handle/$', views.register_handle, name="register_handle"),
    url(r'^register_exist/$', views.register_exist, name="register_exist"),
    url(r'^login/$', views.login, name="login"),
    url(r'^login_handle/$', views.login_handle, name="login_handle"),
    url(r'^info/$', views.info, name="info"),
    url(r'^order/(\d+)$',views.order, name="order"),
    url(r'^site/$', views.site, name="site"),
    url(r'^logout/$', views.logout, name="logout"),
]

bookstore_online/bookstore_online/urls.py
#coding=utf-8
"""bookstore_online URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('bookstore_goods.urls', namespace='bookstore_goods')),
    url(r'^user/', include('bookstore_user.urls', namespace='bookstore_user')),
    url(r'^cart/', include('bookstore_cart.urls', namespace='bookstore_cart')),
    url(r'^order/', include('bookstore_order.urls', namespace='bookstore_order')),
    url(r'^tinymce/', include('tinymce.urls')),  # 使用富文本编辑框配置conf
]

bookstore_online/templates/base.html
{% extends 'base_foot.html' %}

{% block body %}

    <div class="header_con">
		<div class="header">
			<div class="welcome fl">welcome to 在线书店!</div>
			<div class="fr">
{#                判断是否已经登录#}
                {% if request.session.user_name|default:'' != '' %}
{#                    default过滤器进行判断如果request.session.user_name不等于空字符串则用户登录状态为true#}
{#                    也就是说当用户为已登录状态时则显示用户名#}

{#                    class="login_info fl"#}
				<div class="login_btn fl">欢迎您：<em>{{ request.session.user_name }}</em>
                    <span>|</span>
                    <em><a href="{% url "bookstore_user:logout" %}">退出</a></em>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url "bookstore_user:login" %}">登录</a>
					<span>|</span>
					<a href="{% url "bookstore_user:register" %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url "bookstore_user:info" %}">用户中心</a>
					<span>|</span>
					<a href="{% url "bookstore_cart:cart" %}">我的购物车</a>
					<span>|</span>
					<a href="{% url "bookstore_user:order" 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>


    <div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo02.png"></a>
        {% if page_name == 1 %}
            <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{ title }}</div>
        {% endif %}
		<div class="search_con fl">
             <script>
                $(function () {
                    $('.input_btn').click(function () {
    {#                    alert('ok');#}
                        q = $('.input_text').val();
                        location.href = '{% url "bookstore_goods:ordinary_search" %}?q='+q+'&page=1'
                    })
                })

            </script>
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>

        {% if guest_cart == 1 %}
            <div class="guest_cart fr">
                <a href="{% url "bookstore_cart:cart" %}" class="cart_name fl">我的购物车</a>
                <div class="goods_count fl" id="show_count">{{ cart_num }}</div>
            </div>
        {% endif %}
	</div>




{% block content %}
{% endblock content %}
{% block center_body %}

{% endblock center_body %}


{% endblock body %}

bookstore_online/templates/base_foot.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{{ title }} | 在线书店</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
{#	<script type="text/javascript" src="/static/js/register.js"></script>#}
    {% block head %}{% endblock head %}
</head>
<body>

{% block body %}{% endblock body %}

    <div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2019 毕业设计</p>
	</div>

</body>
</html>